const ALERT = "ALERT";
const FEFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MASSAGE = "NEW_MASSAGE";

const NEW_REQUEST = "NEW_REQUEST";

// SOCKET EVENTS
const NEW_MASSAGES = "NEW_MASSAGES";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOPE_TYPING";

export {
  ALERT,
  FEFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MASSAGE,
  NEW_REQUEST,
  NEW_MASSAGES,
  START_TYPING,
  STOP_TYPING,
};
