const ALERT = "ALERT";
const FEFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MASSAGE = "NEW_MASSAGE";

export { ALERT, FEFETCH_CHATS, NEW_ATTACHMENT, NEW_MASSAGE };
