const ALERT = "ALERT";
const FEFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MASSAGE = "NEW_MASSAGE";

const NEW_REQUEST = "NEW_REQUEST";

export { ALERT, FEFETCH_CHATS, NEW_ATTACHMENT, NEW_MASSAGE, NEW_REQUEST };
